language: node_js

install:
  - sudo chown -R $(whoami) /usr/local/bin
  - curl -sf https://up.apex.sh/install | sh
  - up upgrade
  - up version
  - yarn global add node-prune
  - yarn

cache: yarn

script:
  - yarn test

deploy:
  provider: script
  script: sh ./up-deploy.sh
  skip_cleanup: true
  on:
    branch: master

after_success:
  - up url

env:
  global:
    AWS_REGION: us-west-2
