image: node:alpine

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - apk add --no-cache ssh
          - yarn install
          - yarn test
          - yarn build
          - export IMAGE_NAME=winfield/ciri-api:latest
          - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
          - docker build -t $IMAGE_NAME .
          - docker push $IMAGE_NAME
          - ssh $HOST -l $USER 'docker stack deploy -c $COMPOSE_FILE ciri'
